[package]
name = "recursive-dice-roller"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.1.8"
itertools = "0.10.5"
rand = "0.8.5"
